apiVersion: apps/v1
kind: Deployment
metadata:
  name: envspringapp-dep
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: envspringapp
  template:
    metadata:
      labels:
        app: envspringapp
        version: v{{Version}}
    spec:
      containers:
      - name: envspringapp
        image: keyxunlocker/rnd:{{Image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ANI
            valueFrom:
              secretKeyRef:
                name: envspringapp-secr
                key: ani
        volumeMounts:
          - name: config-volume
            mountPath: "/config"
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: envspringapp-config
            items:
              - key: application.yml
                path: application.yml
